server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MySQL_USERNAME}
    password: ${MySQL_PASSWORD}
    url: ${MySQL_URL}

  jpa:
    hibernate:
      generate-ddl: true
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
        auth: true
        starttls:
          enable: true
        ssl:
          trust: smtp.gmail.com
          protocols: TLSv1.2

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

code:
  exp: ${EXP}

logging:
  level:
    "[org.hibernate]": ERROR


