server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://team-project.cqglzcfmqaha.ap-northeast-2.rds.amazonaws.com:3306/auth?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: rhqmffls13!

  jpa:
    hibernate:
      generate-ddl: true
      ddl-auto: update
    show-sql: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: leejeongyoon0411@gmail.com
    password: rhqmffls13!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
            protocols: TLSv1.2
